import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {
          `
          h2{
            font-size:38px;
          }
          h3{
            font-size:28px
          }
          `
        }
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className=''>Hunting Coder</span> 
        </h1>
        <div className={styles.imgWrap}>
          <Image src="/homeimg.jpg" className={styles.myImg} width={237} height={158} />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022</h3>
            <p>JavaScript is the language used to design the logic behind web</p>
          </div>
            <div className="blogItem">
            <h3>How to learn JavaScript in 2022</h3>
            <p>JavaScript is the language used to design the logic behind web</p>
          </div>
            <div className="blogItem">
            <h3>How to learn JavaScript in 2022</h3>
            <p>JavaScript is the language used to design the logic behind web</p>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
